module.exports = {
  // === PRONOUNS ===
  'i':'eu','you':'voce','he':'ele','she':'ela','it':'isso','we':'nos','they':'eles',
  'me':'mim','him':'ele','her':'ela','us':'nos','them':'eles','my':'meu','your':'seu',
  'his':'dele','her':'dela','its':'seu','our':'nosso','their':'deles','mine':'meu',
  'yours':'seu','hers':'dela','ours':'nosso','theirs':'deles',
  'myself':'eu mesmo','yourself':'voce mesmo','himself':'ele mesmo','herself':'ela mesma',
  'itself':'si mesmo','ourselves':'nos mesmos','themselves':'eles mesmos',
  'this':'este','that':'aquele','these':'estes','those':'aqueles',

  // === COMMON VERBS ===
  'be':'ser','am':'sou','is':'e','are':'sao','was':'era','were':'eram','been':'estive','being':'sendo',
  'have':'ter','has':'tem','had':'tinha','having':'tendo',
  'do':'fazer','does':'faz','did':'fez','done':'feito','doing':'fazendo',
  'say':'dizer','says':'diz','said':'disse','saying':'dizendo',
  'get':'pegar','gets':'pega','got':'pegou','gotten':'pegado','getting':'pegando',
  'make':'fazer','makes':'faz','made':'fez','making':'fazendo',
  'go':'ir','goes':'vai','went':'foi','gone':'ido','going':'indo',
  'know':'saber','knows':'sabe','knew':'soube','known':'sabido','knowing':'sabendo',
  'take':'pegar','takes':'pega','took':'pegou','taken':'pegado','taking':'pegando',
  'see':'ver','sees':'ve','saw':'viu','seen':'visto','seeing':'vendo',
  'come':'vir','comes':'vem','came':'veio','coming':'vindo',
  'think':'pensar','thinks':'pensa','thought':'pensou','thinking':'pensando',
  'look':'olhar','looks':'olha','looked':'olhou','looking':'olhando',
  'want':'querer','wants':'quer','wanted':'queria','wanting':'querendo',
  'give':'dar','gives':'da','gave':'deu','given':'dado','giving':'dando',
  'use':'usar','uses':'usa','used':'usou','using':'usando',
  'find':'encontrar','finds':'encontra','found':'encontrou','finding':'encontrando',
  'tell':'contar','tells':'conta','told':'contou','telling':'contando',
  'ask':'perguntar','asks':'pergunta','asked':'perguntou','asking':'perguntando',
  'work':'trabalhar','works':'trabalha','worked':'trabalhou','working':'trabalhando',
  'seem':'parecer','seems':'parece','seemed':'pareceu','seeming':'parecendo',
  'feel':'sentir','feels':'sente','felt':'sentiu','feeling':'sentindo',
  'try':'tentar','tries':'tenta','tried':'tentou','trying':'tentando',
  'leave':'sair','leaves':'sai','left':'saiu','leaving':'saindo',
  'call':'ligar','calls':'liga','called':'ligou','calling':'ligando',
  'keep':'manter','keeps':'mantem','kept':'manteve','keeping':'mantendo',
  'let':'deixar','lets':'deixa','let':'deixou','letting':'deixando',
  'begin':'comecar','begins':'comeca','began':'comecou','begun':'comecado',
  'show':'mostrar','shows':'mostra','showed':'mostrou','shown':'mostrado',
  'hear':'ouvir','hears':'ouve','heard':'ouviu','hearing':'ouvindo',
  'play':'jogar','plays':'joga','played':'jogou','playing':'jogando',
  'run':'correr','runs':'corre','ran':'correu','running':'correndo',
  'move':'mover','moves':'move','moved':'moveu','moving':'movendo',
  'live':'viver','lives':'vive','lived':'viveu','living':'vivendo',
  'believe':'acreditar','believes':'acredita','believed':'acreditou','believing':'acreditando',
  'bring':'trazer','brings':'traz','brought':'trouxe','bringing':'trazendo',
  'happen':'acontecer','happens':'acontece','happened':'aconteceu','happening':'acontecendo',
  'write':'escrever','writes':'escreve','wrote':'escreveu','written':'escrito','writing':'escrevendo',
  'provide':'fornecer','provides':'fornece','provided':'forneceu','providing':'fornecendo',
  'sit':'sentar','sits':'senta','sat':'sentou','sitting':'sentado',
  'stand':'ficar em pe','stands':'fica','stood':'ficou','standing':'em pe',
  'lose':'perder','loses':'perde','lost':'perdeu','losing':'perdendo',
  'pay':'pagar','pays':'paga','paid':'pagou','paying':'pagando',
  'meet':'conhecer','meets':'conhece','met':'conheceu','meeting':'conhecendo',
  'include':'incluir','includes':'inclui','included':'incluiu','including':'incluindo',
  'continue':'continuar','continues':'continua','continued':'continuou','continuing':'continuando',
  'set':'definir','sets':'define','set':'definiu','setting':'definindo',
  'learn':'aprender','learns':'aprende','learned':'aprendeu','learning':'aprendendo',
  'change':'mudar','changes':'muda','changed':'mudou','changing':'mudando',
  'lead':'liderar','leads':'lidera','led':'liderou','leading':'liderando',
  'understand':'entender','understands':'entende','understood':'entendeu','understanding':'entendendo',
  'watch':'assistir','watches':'assiste','watched':'assistiu','watching':'assistindo',
  'follow':'seguir','follows':'segue','followed':'seguiu','following':'seguindo',
  'stop':'parar','stops':'para','stopped':'parou','stopping':'parando',
  'create':'criar','creates':'cria','created':'criou','creating':'criando',
  'speak':'falar','speaks':'fala','spoke':'falou','spoken':'falado','speaking':'falando',
  'read':'ler','reads':'le','read':'leu','reading':'lendo',
  'allow':'permitir','allows':'permite','allowed':'permitiu','allowing':'permitindo',
  'add':'adicionar','adds':'adiciona','added':'adicionou','adding':'adicionando',
  'spend':'gastar','spends':'gasta','spent':'gastou','spending':'gastando',
  'grow':'crescer','grows':'cresce','grew':'cresceu','grown':'crescido','growing':'crescendo',
  'open':'abrir','opens':'abre','opened':'abriu','opening':'abrindo',
  'walk':'andar','walks':'anda','walked':'andou','walking':'andando',
  'win':'vencer','wins':'vence','won':'venceu','winning':'vencendo',
  'offer':'oferecer','offers':'oferece','offered':'ofereceu','offering':'oferecendo',
  'remember':'lembrar','remembers':'lembra','remembered':'lembrou','remembering':'lembrando',
  'love':'amar','loves':'ama','loved':'amou','loving':'amando',
  'buy':'comprar','buys':'compra','bought':'comprou','buying':'comprando',
  'wait':'esperar','waits':'espera','waited':'esperou','waiting':'esperando',
  'die':'morrer','dies':'morre','died':'morreu','dying':'morrendo',
  'send':'enviar','sends':'envia','sent':'enviou','sending':'enviando',
  'build':'construir','builds':'constroi','built':'construiu','building':'construindo',
  'stay':'ficar','stays':'fica','stayed':'ficou','staying':'ficando',
  'fall':'cair','falls':'cai','fell':'caiu','fallen':'caido','falling':'caindo',
  'cut':'cortar','cuts':'corta','cut':'cortou','cutting':'cortando',
  'reach':'alcancar','reaches':'alcanca','reached':'alcancou','reaching':'alcancando',
  'kill':'matar','kills':'mata','killed':'matou','killing':'matando',
  'eat':'comer','eats':'come','ate':'comeu','eaten':'comido','eating':'comendo',
  'carry':'carregar','carries':'carrega','carried':'carregou','carrying':'carregando',
  'hope':'esperar','hopes':'espera','hoped':'esperou','hoping':'esperando',
  'talk':'falar','talks':'fala','talked':'falou','talking':'falando',
  'break':'quebrar','breaks':'quebra','broke':'quebrou','broken':'quebrado','breaking':'quebrando',
  'receive':'receber','receives':'recebe','received':'recebeu','receiving':'recebendo',
  'agree':'concordar','agrees':'concorda','agreed':'concordou','agreeing':'concordando',
  'support':'apoiar','supports':'apoia','supported':'apoiou','supporting':'apoiando',
  'hit':'bater','hits':'bate','hit':'bateu','hitting':'batendo',
  'catch':'pegar','catches':'pega','caught':'pegou','catching':'pegando',
  'draw':'desenhar','draws':'desenha','drew':'desenhou','drawn':'desenhado','drawing':'desenhando',
  'choose':'escolher','chooses':'escolhe','chose':'escolheu','chosen':'escolhido','choosing':'escolhendo',
  'drive':'dirigir','drives':'dirige','drove':'dirigiu','driven':'dirigido','driving':'dirigindo',
  'drink':'beber','drinks':'bebe','drank':'bebeu','drunk':'bebido','drinking':'bebendo',
  'sing':'cantar','sings':'canta','sang':'cantou','sung':'cantado','singing':'cantando',
  'swim':'nadar','swims':'nada','swam':'nadou','swum':'nadado','swimming':'nadando',
  'fly':'voar','flies':'voa','flew':'voou','flown':'voado','flying':'voando',
  'hide':'esconder','hides':'esconde','hid':'escondeu','hidden':'escondido','hiding':'escondendo',
  'forget':'esquecer','forgets':'esquece','forgot':'esqueceu','forgotten':'esquecido',
  'wake':'acordar','wakes':'acorda','woke':'acordou','woken':'acordado','waking':'acordando',
  'wear':'vestir','wears':'veste','wore':'vestiu','worn':'vestido','wearing':'vestindo',
  'throw':'jogar','throws':'joga','threw':'jogou','thrown':'jogado','throwing':'jogando',
  'rise':'subir','rises':'sobe','rose':'subiu','risen':'subido','rising':'subindo',
  'teach':'ensinar','teaches':'ensina','taught':'ensinou','teaching':'ensinando',
  'shake':'sacudir','shakes':'sacode','shook':'sacudiu','shaken':'sacudido','shaking':'sacudindo',
  'shoot':'atirar','shoots':'atira','shot':'atirou','shooting':'atirando',
  'burn':'queimar','burns':'queima','burned':'queimou','burning':'queimando',
  'dream':'sonhar','dreams':'sonha','dreamed':'sonhou','dreaming':'sonhando',
  'wish':'desejar','wishes':'deseja','wished':'desejou','wishing':'desejando',
  'hate':'odiar','hates':'odeia','hated':'odiou','hating':'odiando',
  'miss':'sentir falta','misses':'sente falta','missed':'sentiu falta','missing':'sentindo falta',
  'need':'precisar','needs':'precisa','needed':'precisou','needing':'precisando',
  'like':'gostar','likes':'gosta','liked':'gostou','liking':'gostando',
  'hurt':'machucar','hurts':'machuca','hurt':'machucou','hurting':'machucando',
  'cry':'chorar','cries':'chora','cried':'chorou','crying':'chorando',
  'laugh':'rir','laughs':'ri','laughed':'riu','laughing':'rindo',
  'fight':'lutar','fights':'luta','fought':'lutou','fighting':'lutando',
  'hold':'segurar','holds':'segura','held':'segurou','holding':'segurando',
  'turn':'virar','turns':'vira','turned':'virou','turning':'virando',
  'close':'fechar','closes':'fecha','closed':'fechou','closing':'fechando',
  'start':'comecar','starts':'comeca','started':'comecou','starting':'comecando',
  'pull':'puxar','pulls':'puxa','pulled':'puxou','pulling':'puxando',
  'help':'ajudar','helps':'ajuda','helped':'ajudou','helping':'ajudando',
  'save':'salvar','saves':'salva','saved':'salvou','saving':'salvando',
  'travel':'viajar','travels':'viaja','traveled':'viajou','traveling':'viajando',
  'dance':'dancar','dances':'danca','danced':'dancou','dancing':'dancando',

  // === NOUNS ===
  'time':'tempo','year':'ano','people':'pessoas','way':'caminho','day':'dia','man':'homem',
  'woman':'mulher','child':'crianca','world':'mundo','life':'vida','hand':'mao','part':'parte',
  'place':'lugar','case':'caso','week':'semana','company':'empresa','system':'sistema',
  'program':'programa','question':'pergunta','government':'governo','number':'numero',
  'night':'noite','point':'ponto','home':'lar','water':'agua','room':'quarto','mother':'mae',
  'area':'area','money':'dinheiro','story':'historia','fact':'fato','month':'mes',
  'lot':'muito','right':'direito','study':'estudo','book':'livro','eye':'olho','job':'trabalho',
  'word':'palavra','business':'negocio','issue':'questao','side':'lado','kind':'tipo',
  'head':'cabeca','house':'casa','service':'servico','friend':'amigo','father':'pai',
  'power':'poder','hour':'hora','game':'jogo','line':'linha','end':'fim','member':'membro',
  'law':'lei','car':'carro','city':'cidade','name':'nome','team':'time','minute':'minuto',
  'idea':'ideia','kid':'crianca','body':'corpo','information':'informacao','back':'costas',
  'face':'rosto','level':'nivel','office':'escritorio','door':'porta','health':'saude',
  'person':'pessoa','art':'arte','party':'festa','school':'escola','student':'estudante',
  'paper':'papel','food':'comida','sun':'sol','war':'guerra','music':'musica','movie':'filme',
  'song':'musica','garden':'jardim','river':'rio','sea':'mar','ocean':'oceano',
  'mountain':'montanha','tree':'arvore','flower':'flor','star':'estrela','moon':'lua',
  'sky':'ceu','cloud':'nuvem','rain':'chuva','snow':'neve','wind':'vento','fire':'fogo',
  'earth':'terra','air':'ar','ground':'chao','street':'rua','road':'estrada',
  'bridge':'ponte','building':'predio','church':'igreja','hospital':'hospital',
  'bank':'banco','market':'mercado','store':'loja','table':'mesa','chair':'cadeira',
  'bed':'cama','window':'janela','wall':'parede','heart':'coracao','blood':'sangue',
  'hair':'cabelo','finger':'dedo','foot':'pe','arm':'braco','leg':'perna','mouth':'boca',
  'nose':'nariz','ear':'orelha','neck':'pescoco','voice':'voz','letter':'carta',
  'answer':'resposta','reason':'razao','death':'morte','age':'idade','class':'classe',
  'family':'familia','history':'historia','love':'amor','hope':'esperanca','fear':'medo',
  'anger':'raiva','joy':'alegria','truth':'verdade','secret':'segredo','fate':'destino',
  'luck':'sorte','king':'rei','queen':'rainha','angel':'anjo','devil':'diabo','god':'deus',
  'heaven':'ceu','hell':'inferno','spirit':'espirito','soul':'alma','ghost':'fantasma',
  'monster':'monstro','shadow':'sombra','light':'luz','sound':'som','noise':'barulho',
  'silence':'silencioso','moment':'momento','memory':'memoria','feeling':'sentimento',
  'thought':'pensamento','nightmare':'pesadelo','wonder':'maravilha','magic':'magia',
  'adventure':'aventura','journey':'jornada','dream':'sonho','enemy':'inimigo',
  'stranger':'estranho','neighbor':'vizinho','teacher':'professor','doctor':'medico',
  'leader':'lider','fool':'tolo','hero':'heroi','villain':'vilao','genius':'genio',
  'baby':'bebe','boy':'garoto','girl':'garota','adult':'adulto',
  'brother':'irmao','sister':'irma','son':'filho','daughter':'filha','uncle':'tio',
  'aunt':'tia','husband':'marido','wife':'esposa','boyfriend':'namorado',
  'girlfriend':'namorada','wedding':'casamento','birthday':'aniversario',

  // === ADJECTIVES ===
  'good':'bom','bad':'ruim','new':'novo','old':'velho','first':'primeiro','last':'ultimo',
  'long':'longo','short':'curto','great':'otimo','little':'pequeno','own':'proprio',
  'other':'outro','same':'mesmo','big':'grande','small':'pequeno','large':'grande',
  'high':'alto','low':'baixo','different':'diferente','next':'proximo','young':'jovem',
  'important':'importante','right':'certo','wrong':'errado','true':'verdadeiro',
  'real':'real','full':'cheio','free':'livre','sure':'certo','strong':'forte',
  'weak':'fraco','beautiful':'lindo','pretty':'bonito','ugly':'feio','tall':'alto',
  'short':'baixo','fat':'gordo','thin':'magro','heavy':'pesado','light':'leve',
  'hard':'dificil','easy':'facil','soft':'macio','smooth':'suave','fast':'rapido',
  'slow':'devagar','quick':'rapido','clean':'limpo','dirty':'sujo','rich':'rico',
  'poor':'pobre','deep':'fundo','hot':'quente','cold':'frio','warm':'morno',
  'cool':'legal','dark':'escuro','bright':'claro','smart':'inteligente',
  'wise':'sabio','kind':'gentil','mean':'malvado','nice':'legal','sweet':'doce',
  'happy':'feliz','sad':'triste','angry':'bravo','calm':'calmo','nervous':'nervoso',
  'excited':'animado','bored':'entediado','confused':'confuso','surprised':'surpreso',
  'scared':'com medo','brave':'corajoso','proud':'orgulhoso','lonely':'sozinho',
  'alone':'sozinho','together':'juntos','tired':'cansado','sick':'doente',
  'hungry':'com fome','thirsty':'com sede','sleepy':'sonolento','awake':'acordado',
  'alive':'vivo','dead':'morto','ready':'pronto','early':'cedo','late':'tarde',
  'safe':'seguro','dangerous':'perigoso','broken':'quebrado','open':'aberto',
  'closed':'fechado','empty':'vazio','strange':'estranho','weird':'esquisito',
  'normal':'normal','special':'especial','common':'comum','rare':'raro',
  'simple':'simples','famous':'famoso','popular':'popular','ancient':'antigo',
  'possible':'possivel','impossible':'impossivel','funny':'engracado','serious':'serio',
  'lucky':'sortudo','wonderful':'maravilhoso','terrible':'terrivel',
  'amazing':'incrivel','perfect':'perfeito','favorite':'favorito',
  'curious':'curioso','honest':'honesto','loyal':'leal','polite':'educado',
  'rude':'grosseiro','selfish':'egoista','generous':'generoso','lazy':'preguicoso',
  'shy':'timido','confident':'confiante','jealous':'ciumento','crazy':'louco',
  'wild':'selvagem','pure':'puro','evil':'maligno','holy':'santo',
  'secret':'secreto','public':'publico','foreign':'estrangeiro','local':'local',
  'personal':'pessoal','private':'privado','sudden':'repentino',

  // === ADVERBS ===
  'very':'muito','too':'demais','also':'tambem','always':'sempre','never':'nunca',
  'often':'frequentemente','sometimes':'as vezes','usually':'geralmente','already':'ja',
  'yet':'ainda','still':'ainda','again':'novamente','ever':'alguma vez','just':'apenas',
  'only':'somente','so':'entao','then':'entao','now':'agora','here':'aqui','there':'ali',
  'where':'onde','why':'por que','how':'como','when':'quando','what':'o que','who':'quem',
  'which':'qual','maybe':'talvez','almost':'quase','quite':'bastante',
  'really':'realmente','probably':'provavelmente','absolutely':'absolutamente',
  'together':'juntos','inside':'dentro','outside':'fora','above':'acima','below':'abaixo',
  'before':'antes','after':'depois','today':'hoje','tomorrow':'amanha','yesterday':'ontem',

  // === -LY ADVERBS ===
  'slowly':'devagar','quickly':'rapidamente','loudly':'alto','softly':'suavemente',
  'gently':'suavemente','quietly':'silenciosamente','badly':'mal','deeply':'profundamente',
  'highly':'altamente','closely':'de perto','nearly':'quase','barely':'mal',
  'hardly':'dificilmente','simply':'simplesmente','truly':'verdadeiramente',
  'freely':'livremente','totally':'totalmente','completely':'completamente',
  'absolutely':'absolutamente','entirely':'inteiramente','perfectly':'perfeitamente',
  'certainly':'certamente','definitely':'definitivamente','clearly':'claramente',
  'suddenly':'repentinamente','immediately':'imediatamente','directly':'diretamente',
  'easily':'facilmente','carefully':'cuidadosamente','secretly':'secretamente',
  'silently':'silenciosamente','proudly':'orgulhosamente','bravely':'corajosamente',
  'honestly':'honestamente','sadly':'tristemente','luckily':'felizmente',
  'exactly':'exatamente','especially':'especialmente','possibly':'possivelmente',
  'briefly':'brevemente','lightly':'levemente','heavily':'pesadamente',
  'brightly':'brilhantemente','purely':'puramente','tightly':'apertadamente',
  'lately':'ultimamente','rarely':'raramente','merely':'meramente',

  // === -ING FORMS ===
  'riding':'andando de','driving':'dirigindo','walking':'andando','running':'correndo',
  'swimming':'nadando','flying':'voando','singing':'cantando','dancing':'dancando',
  'crying':'chorando','laughing':'rindo','smiling':'sorrindo','talking':'falando',
  'saying':'dizendo','telling':'contando','asking':'perguntando','waiting':'esperando',
  'looking':'olhando','watching':'assistindo','listening':'ouvindo','feeling':'sentindo',
  'thinking':'pensando','knowing':'sabendo','trying':'tentando','doing':'fazendo',
  'making':'fazendo','taking':'pegando','giving':'dando','getting':'pegando',
  'going':'indo','coming':'vindo','leaving':'saindo','staying':'ficando',
  'living':'vivendo','dying':'morrendo','sleeping':'dormindo','waking':'acordando',
  'dreaming':'sonhando','wishing':'desejando','hoping':'esperando','loving':'amando',
  'hating':'odiando','needing':'precisando','wanting':'querendo','sharing':'compartilhando',
  'breaking':'quebrando','shaking':'sacudindo','burning':'queimando','falling':'caindo',
  'rising':'subindo','changing':'mudando','turning':'virando','moving':'movendo',
  'playing':'jogando','working':'trabalhando','reading':'lendo','writing':'escrevendo',
  'sitting':'sentado','lying':'deitado','fighting':'lutando','winning':'vencendo',
  'losing':'perdendo','learning':'aprendendo','teaching':'ensinando','growing':'crescendo',
  'searching':'procurando','finding':'encontrando','holding':'segurando',
  'bringing':'trazendo','beginning':'comecando','ending':'terminando',
  'following':'seguindo','opening':'abrindo','closing':'fechando',
  'starting':'comecando','stopping':'parando','helping':'ajudando','saving':'salvando',

  // === COMPARATIVES / SUPERLATIVES ===
  'better':'melhor','worse':'pior','bigger':'maior','smaller':'menor','faster':'mais rapido',
  'slower':'mais devagar','higher':'mais alto','lower':'mais baixo','deeper':'mais fundo',
  'longer':'mais longo','shorter':'mais curto','older':'mais velho','younger':'mais novo',
  'closer':'mais perto','farther':'mais longe','stronger':'mais forte','weaker':'mais fraco',
  'harder':'mais duro','softer':'mais macio','richer':'mais rico','poorer':'mais pobre',
  'warmer':'mais quente','colder':'mais frio','hotter':'mais quente','cooler':'mais frio',
  'darker':'mais escuro','brighter':'mais claro','happier':'mais feliz','sadder':'mais triste',
  'angrier':'mais bravo','easier':'mais facil','earlier':'mais cedo','later':'mais tarde',
  'best':'melhor','worst':'pior','biggest':'maior','smallest':'menor',
  'fastest':'mais rapido','highest':'mais alto','deepest':'mais fundo','longest':'mais longo',
  'oldest':'mais velho','strongest':'mais forte','happiest':'mais feliz',

  // === SONGS / LYRICS ===
  'tonight':'hoje a noite','forever':'para sempre','somewhere':'em algum lugar',
  'anywhere':'em qualquer lugar','everywhere':'em todo lugar','nowhere':'em lugar nenhum',
  'beneath':'debaixo','beyond':'alem','against':'contra','between':'entre','among':'entre',
  'through':'atraves','without':'sem','midnight':'meia noite','dawn':'amanhecer',
  'dusk':'anoitecer','sunrise':'nascer do sol','sunset':'por do sol',
  'paradise':'paraiso','thunder':'trovao','lightning':'relampago','hurricane':'furacao',
  'flood':'inundacao','blossom':'flor','valley':'vale','desert':'deserto','island':'ilha',
  'cave':'caverna','forest':'floresta','jungle':'selva','lake':'lago','pond':'lagoa',
  'stream':'riacho','waterfall':'cachoeira','wave':'onda','tide':'mare',
  'moonlight':'luar','twilight':'crepusculo','rainbow':'arco iris',
  'butterfly':'borboleta','spider':'aranha','snake':'cobra','eagle':'aguia',
  'wolf':'lobo','bear':'urso','lion':'leao','tiger':'tigre','whale':'baleia',
  'dolphin':'golfinho','horse':'cavalo','sheep':'ovelha','silver':'prata','gold':'ouro',
  'diamond':'diamante','stone':'pedra','rock':'rocha','crystal':'cristal','glass':'vidro',
  'mirror':'espelho','gate':'portao','tower':'torre','castle':'castelo','palace':'palacio',
  'battle':'batalha','warrior':'guerreiro','sword':'espada','shield':'escudo',
  'crown':'coroa','throne':'trono','prayer':'oracao','curse':'maldicao','witch':'bruxa',
  'candle':'vela','whisper':'sussurro','echo':'eco','melody':'melodia','rhythm':'ritmo',
  'harmony':'harmonia','chorus':'refrao','verse':'estrofe','drum':'bateria',
  'guitar':'violao','piano':'piano','courage':'coragem','passion':'paixao',
  'mercy':'misericordia','grace':'graca','glory':'gloria','honor':'honra',
  'pride':'orgulho','shame':'vergonha','blame':'culpa','wrath':'ira','greed':'ganancia',
  'envy':'inveja','forgiveness':'perdao','redemption':'redencao','salvation':'salvacao',
  'destruction':'destruicao','sorrow':'tristeza','grief':'luto','despair':'desespero',
  'bliss':'felicidade','mystery':'misterio',

  // === PAST TENSE IRREGULAR VERBS ===
  'became':'tornou-se','began':'comecou','bent':'dobrou','bled':'sangrou','blew':'soprou',
  'broke':'quebrou','brought':'trouxe','built':'construiu','burnt':'queimou',
  'burst':'explodiu','bought':'comprou','cast':'lancou','caught':'pegou',
  'chose':'escolheu','crept':'rastejou','drew':'desenhou','drank':'bebeu','drove':'dirigiu',
  'ate':'comeu','fell':'caiu','fed':'alimentou','fled':'fugiu','flew':'voou',
  'forgave':'perdoou','froze':'congelou','grew':'cresceu','hid':'escondeu',
  'held':'segurou','led':'liderou','lit':'acendeu','meant':'significou','paid':'pagou',
  'quit':'saiu','rang':'tocou','rose':'subiu','sank':'afundou','saw':'viu',
  'sold':'vendeu','sent':'enviou','shook':'sacudiu','shone':'brilhou','shot':'atirou',
  'shut':'fechou','sang':'cantou','sat':'sentou','slept':'dormiu','slid':'escorregou',
  'spoke':'falou','spent':'gastou','spun':'girou','split':'dividiu','spread':'espalhou',
  'stole':'roubou','stuck':'ficou preso','stung':'picou','struck':'atingiu',
  'swore':'jurou','swept':'varreu','swam':'nadou','swung':'balancou','took':'pegou',
  'taught':'ensinou','tore':'rasgou','thought':'pensou','threw':'jogou',
  'understood':'entendeu','upset':'perturbou','woke':'acordou','wore':'vestiu',
  'wept':'chorou','won':'venceu','wrote':'escreveu',

  // === MODAL VERBS ===
  'can':'pode','could':'poderia','will':'vai','would':'iria','shall':'deve',
  'should':'deveria','may':'pode','might':'talvez','must':'deve',

  // === CONTRACTIONS ===
  'dont':'nao','cant':'nao pode','wont':'nao vai','didnt':'nao fez','isnt':'nao e',
  'arent':'nao sao','wasnt':'nao era','werent':'nao eram','havent':'nao tem',
  'hasnt':'nao tem','hadnt':'nao tinha','couldnt':'nao podia','wouldnt':'nao iria',
  'shouldnt':'nao deveria','mustnt':'nao deve',
  'im':'eu sou','youre':'voce e','hes':'ele e','shes':'ela e','its':'e',
  'theyre':'eles sao','ive':'eu tenho','youve':'voce tem','weve':'nos temos',
  'theyve':'eles tem','id':'eu iria','youd':'voce iria','hed':'ele iria',
  'shed':'ela iria','wed':'nos iriamos','theyd':'eles iriam','lets':'vamos',
  'thats':'isso e','theres':'ha','heres':'aqui esta','whos':'quem e',
  'whats':'o que e','whens':'quando e','wheres':'onde esta',
  'gonna':'vou','wanna':'quero','gotta':'tenho que','gimme':'me da','outta':'fora',
  'kinda':'meio que','sorta':'mais ou menos','lotta':'muito','dunno':'nao sei',
  'cause':'porque','yeah':'sim','nah':'nao','yep':'sim','nope':'nao',
  'guy':'cara','guys':'galera','ok':'ok','alright':'tudo bem','hello':'ola','hi':'oi',
  'hey':'ei','bye':'tchau','sorry':'desculpe','please':'por favor',
  'thanks':'obrigado','welcome':'bem vindo',
  'yes':'sim','no':'nao','not':'nao','sure':'claro','okay':'ok',
  'plenty':'bastante','enough':'suficiente','even':'ate',
  'guess':'adivinhar','suppose':'supor',

  // === EXTRA VERBS (past -ed forms & common) ===
  'breathe':'respirar','breathing':'respirando','breathed':'respirou',
  'bleed':'sangrar','bleeding':'sangrando','bled':'sangrou',
  'freeze':'congelar','freezing':'congelando','frozen':'congelado',
  'melt':'derreter','melting':'derretendo','melted':'derreteu',
  'steal':'roubar','stealing':'roubando','stolen':'roubado',
  'slide':'escorregar','sliding':'escorregando','slid':'escorregou',
  'float':'flutuar','floating':'flutuando','floated':'flutuou',
  'drown':'afogar','drowning':'afogando','drowned':'afogou',
  'sink':'afundar','sinking':'afundando','sank':'afundou','sunk':'afundado',
  'climb':'escalar','climbing':'escalando','climbed':'escalou',
  'jump':'pular','jumping':'pulando','jumped':'pulou',
  'stare':'encarar','staring':'encarando','stared':'encarou',
  'glance':'olhadela','glancing':'olhando','glanced':'olhou',
  'weep':'chorar','weeping':'chorando','wept':'chorou',
  'scream':'gritar','screaming':'gritando','screamed':'gritou',
  'shout':'gritar','shouting':'gritando','shouted':'gritou',
  'whisper':'sussurrar','whispering':'sussurrando','whispered':'sussurrou',
  'roar':'rugir','roaring':'rugindo','roared':'rugiu',
  'howl':'uivar','howling':'uivando','howled':'uivou',
  'heal':'curar','healing':'curando','healed':'curou',
  'tremble':'tremer','trembling':'tremendo','trembled':'tremeu',
  'sigh':'suspirar','sighing':'suspirando','sighed':'suspirou',
  'blink':'piscar','blinking':'piscando','blinked':'piscou',
  'frown':'franzir','frowning':'franzindo','frowned':'franziu',
  'kiss':'beijar','kissing':'beijando','kissed':'beijou',
  'hug':'abraçar','hugging':'abraçando','hugged':'abraçou',
  'fade':'desvanecer','fading':'desvanecendo','faded':'desvaneceu',
  'vanish':'desaparecer','vanishing':'desaparecendo','vanished':'desapareceu',
  'appear':'aparecer','appearing':'aparecendo','appeared':'apareceu',
  'disappear':'desaparecer','disappearing':'desaparecendo','disappeared':'desapareceu',
  'glow':'brilhar','glowing':'brilhando','glowed':'brilhou',
  'sparkle':'cintilar','sparkling':'cintilando','sparkled':'cintilou',
  'twinkle':'cintilar','twinkling':'cintilando','twinkled':'cintilou',
  'stumble':'tropecar','stumbling':'tropecando','stumbled':'tropecou',
  'wander':'vagar','wandering':'vagando','wandered':'vagueou',
  'drift':'flutuar','drifting':'flutuando','drifted':'flutuou',
  'sway':'balancar','swaying':'balancando','swayed':'balancou',
  'swing':'balancar','swinging':'balancando','swung':'balancou',
  'spin':'girar','spinning':'girando','spun':'girou',
  'twist':'torcer','twisting':'torcendo','twisted':'torceu',
  'fold':'dobrar','folding':'dobrando','folded':'dobrou',
  'unfold':'desdobrar','unfolding':'desdobrando','unfolded':'desdobrou',
  'wrap':'embrulhar','wrapping':'embrulhando','wrapped':'embrulhou',
  'ignite':'acender','igniting':'acendendo','ignited':'acendeu',
  'explode':'explodir','exploding':'explodindo','exploded':'explodiu',
  'collapse':'colapsar','collapsing':'colapsando','collapsed':'colapsou',
  'shatter':'estilhacar','shattering':'estilhacando','shattered':'estilhaçou',
  'splash':'espirrar','splashing':'espirrando','splashed':'espirrou',
  'pour':'derramar','pouring':'derramando','poured':'derramou',
  'flow':'fluir','flowing':'fluindo','flowed':'fluiu',
  'rush':'apressar','rushing':'apressando','rushed':'apressou',
  'chase':'perseguir','chasing':'perseguindo','chased':'perseguiu',
  'pursue':'perseguir','pursuing':'perseguindo','pursued':'perseguiu',
  'flee':'fugir','fleeing':'fugindo','fled':'fugiu',
  'escape':'escapar','escaping':'escapando','escaped':'escapou',
  'avoid':'evitar','avoiding':'evitando','avoided':'evitou',
  'face':'enfrentar','facing':'enfrentando','faced':'enfrentou',
  'resist':'resistir','resisting':'resistindo','resisted':'resistiu',
  'surrender':'render-se','surrendering':'rendendo-se','surrendered':'rendeu-se',
  'obey':'obedecer','obeying':'obedecendo','obeyed':'obedeceu',
  'defy':'desafiar','defying':'desafiando','defied':'desafiou',
  'betray':'trair','betraying':'traindo','betrayed':'traiu',
  'deceive':'enganar','deceiving':'enganando','deceived':'enganou',
  'blame':'culpar','blaming':'culpando','blamed':'culpou',
  'praise':'elogiar','praising':'elogiando','praised':'elogiou',
  'admire':'admirar','admiring':'admirando','admired':'admirou',
  'respect':'respeitar','respecting':'respeitando','respected':'respeitou',
  'honor':'honrar','honoring':'honrando','honored':'honrou',
  'cherish':'valorizar','cherishing':'valorizando','cherished':'valorizou',
  'guard':'guardar','guarding':'guardando','guarded':'guardou',
  'protect':'proteger','protecting':'protegendo','protected':'protegeu',
  'defend':'defender','defending':'defendendo','defended':'defendeu',
  'attack':'atacar','attacking':'atacando','attacked':'atacou',
  'strike':'atingir','striking':'atingindo','struck':'atingiu',
  'destroy':'destruir','destroying':'destruindo','destroyed':'destruiu',
  'ruin':'arruinar','ruining':'arruinando','ruined':'arruinou',
  'damage':'danificar','damaging':'danificando','damaged':'danificou',
  'repair':'consertar','repairing':'consertando','repaired':'consertou',
  'fix':'consertar','fixing':'consertando','fixed':'consertou',
  'gather':'reunir','gathering':'reunindo','gathered':'reuniu',
  'collect':'coletar','collecting':'coletando','collected':'coletou',
  'scatter':'espalhar','scattering':'espalhando','scattered':'espalhou',
  'separate':'separar','separating':'separando','separated':'separou',
  'divide':'dividir','dividing':'dividindo','divided':'dividiu',
  'unite':'unir','uniting':'unindo','united':'uniu',
  'connect':'conectar','connecting':'conectando','connected':'conectou',
  'lock':'trancar','locking':'trancando','locked':'trancou',
  'unlock':'destrancar','unlocking':'destrancando','unlocked':'destrancou',
  'release':'liberar','releasing':'liberando','released':'liberou',
  'trap':'prender','trapping':'prendendo','trapped':'prendeu',
  'capture':'capturar','capturing':'capturando','captured':'capturou',
  'bother':'incomodar','bothering':'incomodando','bothered':'incomodou',
  'annoy':'irritar','annoying':'irritando','annoyed':'irritou',
  'amuse':'divertir','amusing':'divertindo','amused':'divertiu',
  'entertain':'entreter','entertaining':'entretendo','entertained':'entreteve',
  'excite':'animar','exciting':'animando','excited':'animou',
  'calm':'acalmar','calming':'acalmando','calmed':'acalmou',
  'comfort':'confortar','comforting':'confortando','comforted':'confortou',
  'shock':'chocar','shocking':'chocando','shocked':'chocou',
  'amaze':'surpreender','amazing':'surpreendendo','amazed':'surpreendeu',
  'surprise':'surpreender','surprising':'surpreendendo','surprised':'surpreendeu',
  'confuse':'confundir','confusing':'confundindo','confused':'confundiu',
  'tempt':'tentar','tempting':'tentando','tempted':'tentou',
  'charm':'encantar','charming':'encantando','charmed':'encantou',
  'haunt':'assombrar','haunting':'assombrando','haunted':'assombrou',
};
