name: DAST Scan

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan de Segurança Dinâmico (DAST)
    permissions:
      contents: read
      issues: write
      actions: write
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://lbs-1-pop-lingo.onrender.com'
          fail_action: false

      - name: Upload do Relatório
        uses: actions/upload-artifact@v4
        with:
          name: security-report
          path: report_html.html